
backend:
  name: github
  repo: YOUR-GITHUB-USERNAME/DESCF-WEBSITE-2
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: "https://descf.netlify.app"
display_url: "https://descf.netlify.app"
logo_url: "/assets/images/placeholder-card.svg"

slug:
  encoding: "ascii"
  clean_accents: true
  